

name: build-and-deploy

on:
  push:
    branches:
      - 'main'

env:
  DOCKER_REPOSITORY: juamsv/api-labs
  EKS_CLUSTER_NAME: cluster1
  AWS_REGION: us-east-1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        with:
          context: ./api-labs
          file: ./api-labs/Dockerfile
          load: true
          push: true
          tags: ${{ .env.DOCKER_REPOSITORY}}:${{ env.IMAGE_TAG }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        env:
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
            cd k8s && \
            sed -i 's|image: api-labs:latest|image: juamsv/api-labs:$IMAGE_TAG|' app.yaml && \
            kubectl apply -f app.yaml